const FETCH_BLOGS_REQUEST = 'FETCH_BLOGS_REQUEST'
const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS'
const FETCH_BLOGS_FAILURE = 'FETCH_BLOGS_FAILURE'
const CLEAR_ERRORS = 'CLEAR_ERRORS'
export  {
    FETCH_BLOGS_REQUEST,
    FETCH_BLOGS_SUCCESS,
    FETCH_BLOGS_FAILURE,
    CLEAR_ERRORS
}