const FETCH_BLOGS_REQUEST = 'FETCH_BLOGS_REQUEST'
const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS'
const FETCH_BLOGS_FAILURE = 'FETCH_BLOGS_FAILURE'
const CLEAR_ERRORS = 'CLEAR_ERRORS'
const FETCH_BLOG_DETAILS_REQUEST = 'FETCH_BLOG_DETAILS_REQUEST'
const FETCH_BLOG_DETAILS_SUCCESS = 'FETCH_BLOG_DETAILS_SUCCESS'
const FETCH_BLOG_DETAILS_FAILURE = 'FETCH_BLOG_DETAILS_FAILURE'
export  {
    FETCH_BLOGS_REQUEST,
    FETCH_BLOGS_SUCCESS,
    FETCH_BLOGS_FAILURE,
    CLEAR_ERRORS,
    FETCH_BLOG_DETAILS_REQUEST,
    FETCH_BLOG_DETAILS_SUCCESS,
    FETCH_BLOG_DETAILS_FAILURE
}