const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST';
const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
const CREATE_REVIEW_FAILURE = 'CREATE_REVIEW_FAILURE';
const CLEAR_ERRORS = 'CLEAR_ERRORS';
const FETCH_REVIEW_REQUEST = 'FETCH_REVIEW_REQUEST';
const FETCH_REVIEW_SUCCESS = 'FETCH_REVIEW_SUCCESS';
const FETCH_REVIEW_FAILURE = 'FETCH_REVIEW_FAILURE';
export {
    CREATE_REVIEW_REQUEST,
    CREATE_REVIEW_SUCCESS,
    CREATE_REVIEW_FAILURE,
    CLEAR_ERRORS,
    FETCH_REVIEW_REQUEST,
    FETCH_REVIEW_SUCCESS,
    FETCH_REVIEW_FAILURE
}